# Generated by Django 3.1.5 on 2021-02-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('name', models.TextField()),
                ('role', models.CharField(choices=[('GM', 'General Manager'), ('SM', 'Shift Manager'), ('CS', 'Cashier')], default='CS', max_length=2)),
                ('session_key', models.TextField()),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('employee_id', models.IntegerField(max_length=5)),
                ('active', models.BooleanField()),
                ('role', models.CharField(choices=[('GM', 'General Manager'), ('SM', 'Shift Manager'), ('CS', 'Cashier')], default='CS', max_length=2)),
                ('password', models.TextField()),
                ('created_on', models.DateField()),
            ],
        ),
    ]
